baseURL = "https://osintelproject.org"
languageCode = "en-us"
title = "OSINTEL Project"
theme = "mero"
disableKinds = ["taxonomyTerm"]

[params]
  dateFormat = "2006-01-02"
  author = "OSINTEL Project"
  description = "My awesome blog"
  mainImage = "images/main.jpeg"

[params.introduction]
   text = "This website is my blog. This is to try and display basic writing and analysis skills of current and past events in relation to international affairs."

[params.social]
  [[params.social.list]]
  class = "fab"
  icon = "fa-linkedin-in"
  url = "#"

  [[params.social.list]]
  class = "fab"
  icon = "fa-github"
  url = "https://github.com/OSINTELProject"

  [[params.social.list]]
  class = "fab"
  icon = "fa-twitter"
  url = "https://twitter.com/OOSINTELProject"

  [[params.social.list]]
  class = "fab"
  icon = "fa-stack-overflow"
  url = "#"

[params.footer]
  message = "OSINTEL Project | osintelproject@outlook.com"